### PR TITLE
Broccoli 1.0

### PR DESCRIPTION
**Pull request by acburdine**

### CODE REVIEW

**Comment by davewasmer** [comment]
@acburdine last time I tried upgrading to broccoli 1.0, I ran into issues with `denali-babel`, since `broccoli-babel-transpiler` still uses `0.16.x`. Can you verify that this upgrade won't break denali-babel?

https://github.com/babel/broccoli-babel-transpiler/blob/master/package.json#L47

**Comment by acburdine** [comment]
Yeah - I tested it with my app that uses denali babel and it worked fine. Still has some race conditions that I need to look at but other than that it should be good.

**Comment by davewasmer** [comment]
Okay - any chance we could break out the broccoli upgrade separate from the rest of the upgrades here, and otherwise try to reduce the diff to the bare minimum? Just in case unexpected issues arise, it would be nice to be able to revert out just the broccoli upgrade if we have to.

**Comment by acburdine** [comment]
👍  will try and fix the race condition I'm seeing too - it's really weird and only happens 50% of the time

**Comment by davewasmer** [comment]
Closing for lack of activity.

Don't worry - this doesn't mean I'm not interested in these changes! But unfortunately, I can't merge this in given it's current state. And since there hasn't been much activity here in a while, I'm closing it to try to reduce the clutter.

However - if you (or anyone else!) wants to pick this back up again, I'm more than happy to reopen the PR and pick up the conversation again. Just let me know if you're interested!

**Pull request closed without merging**
